services:
  mongodb:
    image: mongo:7.0.14
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
      - db-config:/data/configdb
  todo-list-api:
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: /todo-list-api
    depends_on:
      - mongodb
    restart: unless-stopped
    image: todo-list-api
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    command: npm run dev

volumes:
  db:
  db-config:
